[workspace]
resolver = "3"
members = ["config-schema", "fruits", "core", "log"]

[workspace.dependencies]
serde = { version = "1", features = ["derive"] }
serde_json = "1"
thiserror = "2"

[patch.crates-io]
log = { path = "log" }
