app: MyConfigsApp
version: 1.0.0

fruit:
  kind: apple
  color: red
  sweetness: 7
  unknown_field: should_warn   # unknown 필드
  options:
    max_price: 5
    season_only: true
  unknown_key_policy: warn     # warn 정책 설정
